# Generated by Django 5.2.8 on 2026-01-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank='True', related_name='categories', to='showcase_app.product'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='showcase_app.product'),
        ),
    ]
